{{ config(materialized='table') }}

        with
        gl_daily_rates as (select * from {{ ref("gl_daily_rates") }}),
ct_gl_daily_rates_d_stg as (
SELECT GL_DAILY_RATES.FROM_CURRENCY AS FROM_CURRENCY, GL_DAILY_RATES.TO_CURRENCY AS TO_CURRENCY, GL_DAILY_RATES.CONVERSION_DATE AS CONVERSION_DT, GL_DAILY_RATES.CONVERSION_TYPE AS CONVERSION_TYPE, GL_DAILY_RATES.CONVERSION_RATE AS CONVERSION_RATE, GL_DAILY_RATES.STATUS_CODE AS STATUS_CODE, GL_DAILY_RATES.CREATION_DATE AS CREATION_DT, GL_DAILY_RATES.CREATED_BY AS CREATED_BY, GL_DAILY_RATES.LAST_UPDATE_DATE AS LAST_UPDATE_DT, GL_DAILY_RATES.LAST_UPDATED_BY AS LAST_UPDATED_BY, GL_DAILY_RATES.LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN, GL_DAILY_RATES.CONTEXT AS CONTEXT, GL_DAILY_RATES.RATE_SOURCE_CODE AS RATE_SOURCE_CODE, GL_DAILY_RATES.CONVERSION_TYPE || '~' || GL_DAILY_RATES.FROM_CURRENCY || '~' || GL_DAILY_RATES.TO_CURRENCY || '~' || TO_CHAR( GL_DAILY_RATES.CONVERSION_DATE, 'MMDDYYYY' ) AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID FROM gl_daily_rates WHERE (1 = 1)
)

        select * from ct_gl_daily_rates_d_stg
